[package]
name = "zakura-grpc-client-example"
version.workspace = true
authors.workspace = true
description = "Command-line examples for the Zakura gRPC Rust client"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
clap = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
zakura-grpc-client = { workspace = true }
zakura-grpc-proto = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "load-test"
path = "src/bin/load-test.rs"
